# OC data: creating spatial hierarchy for Eric Kansa April 2023

# This script explores
# 1. VOronyi approach
# 2. Buffers approach
# 3. Select by distance approach
# 4. might look at neighborhood approach?

# merge units with sites and generate a column that lists either the site TRAP id, or a nonsite_1, nonsite_2. You can use Voronyi polygons too. 

library(sf)
library(raster)
library(tidyverse)

# Choose which computer you are on
path <- "C:/Users/Adela/OneDrive/Desktop/TRAP_Oxbow/"  # path for W11
#path <- "C:/Users/adela/Desktop/TRAP_Oxbow/"        # path for W10

# Load survey polygons
yam <- read_sf("C:/Users/adela/Downloads/yam-survey-units-reproj-w-uuids.geojson")

yam_35 <- st_transform(yam, 32635)

plot(yam$geometry)
names(yam)
st_crs(yam)

# Load site polygons
y_sites <- read_sf(paste0(path, "Yam/yam_margins.shp"))

# aggregate them into multipolygons by TRAP id
y_sitesu <- aggregate(y_sites, by = list(y_sites$TRAP_Code),  do_union = TRUE, FUN = 'mean')


head(y_sites,3)
head(y_sitesu,3)
# plot to see the difference
plot(y_sitesu$geometry) 
y_sites$TRAPid <- factor(y_sites$TRAP_Code)
mapview(y_sitesu) + mapview(y_sites, zcol = "TRAPid")
?aggregate()

#  Load site centroids

yam_sites<- read_sf(paste0(path, "YAM/YAM_scatterpoints.shp"))
plot(yam$geometry);plot(st_transform(yam_sites$geometry, 4326), cex = 2, col = "red", add = T)
st_crs(yam)

# Create buffers
yam_sites_buf <- st_buffer(yam_sites, dist = 500)
y_sitesu_buf <- st_buffer(y_sitesu, dist = 500)

library(mapview)
mapview(yam_sites_buf) + mapview(y_sitesu_buf)
# Load site attributes (chronology)


################################ Join sites and polygons 
# Do spatial join to check how many sites overlap with polygons 
# to join attributes 

yam_join_site <- yam %>% 
  st_transform(32635) %>% 
  st_join(y_sites[,c(2:3,8)])

length(unique(yam_join_site$TRAP_Code)) #24 out of 27 sites are within yam polygons
colnames(yam_join_site)

# check what groupings you get now


###################### Voronyi approach
?st_voronoi()


# need bounding box for yam survey coverage as 
# a second argument

yam_master <- yam %>% 
  st_transform(32635) %>% 
  st_simplify(dTolerance = 50) %>% 
  st_union(by_feature = F) %>% 
  st_buffer(250)

plot(yam_master)
st_bbox(yam_master)
st_bbox(yam_sites)

border <- st_as_sfc(st_bbox(yam_sites))# %>% 
   #st_set_crs(NA)
point <- st_sfc(yam_sites$geometry)
st_crs(border)==st_crs(point)

# Not sure what I did below???
# voronyi <- st_intersection(st_collection_extract(st_voronoi(do.call(c,point))),border)
# st_crs(voronyi) <- 32635
# mapview(voronyi)
?st_voronoi

# Create Voronyi polygons 
# Consider using aggregated polygons for y_sites >> y_sitesu
y_sitepoint_voronyi <- st_voronoi(st_union(yam_sites), envelope = st_as_sfc(st_bbox(yam_sites)))
y_sitepoly_voronyi <- st_voronoi(st_union(st_centroid(y_sitesu)), envelope = st_as_sfc(st_bbox(y_sites)))

# Extract the actual polygons from the collection
sitecentroid_voronyi <- st_collection_extract(y_sitepoint_voronyi)
siteborder_voronyi <- st_collection_extract(y_sitepoly_voronyi)

# Plot voronyi polygons around scatter points and polygon centroids
plot(sitecentroid_voronyi); plot(siteborder_voronyi, border = "red", add = T)

# Plot the voronyi polygons around scatter points
plot(yam_master, col = "pink")
plot(sitecentroid_voronyi, add = T)
plot(yam_sites$geometry, add =T)
plot(st_as_sfc(st_bbox(yam_sites$geometry)), add =T)


# plot voronyi polygons around autogenerated centroids
plot(yam_master, col = "pink")
plot(siteborder_voronyi, add = T)
plot(yam_sites$geometry, add =T)
plot(st_as_sfc(st_bbox(y_sites$geometry)), add =T)

# plot with mapview to zoom in and check on things
mapview(st_sf(siteborder_voronyi)) + mapview(y_sites)+ mapview (yam_master)


## Reduce Voronyi polygons to survey area

plot(st_intersection(sitecentroid_voronyi, yam_master)); plot(y_sites$geometry, add = T)
sitecentroid_voronyi <- st_intersection(sitecentroid_voronyi, yam_master)
siteborder_voronyi <- st_intersection(siteborder_voronyi, yam_master)

plot(siteborder_voronyi)
plot(y_sites$geometry, add = T, col = "purple")

## Join Voronyi with site information
sitecentroid_voronyi <- st_join(st_sf(sitecentroid_voronyi), st_sf(yam_sites))
siteborder_voronyi <- st_join(st_sf(siteborder_voronyi), st_sf(yam_sites))

length(unique(siteborder_voronyi$TRAP_Code))

# Visualise with survey polygons
plot(yam_sites$geometry)
plot(siteborder_voronyi$geometry, col = siteborder_voronyi$TRAP_Code, alpha = 0.5, add =T)


# Intersect survey polygons with Voronyi polygons
list_vor_per_unit <- st_intersects(yam_35,sitecentroid_voronyi)

list_units_per_vor <- st_intersects(sitecentroid_voronyi, yam_35) # list of intersecting units

# Intersection (DOES NOT WORK due to topology)
units_w_vor <- st_intersection(yam_35,sitecentroid_voronyi)
?st_intersection
# to handle lists, I need something alongside: # https://gis.stackexchange.com/questions/375177/in-r-how-do-i-generate-r-random-sample-of-contiguous-polygons

# INtersection sideways
yam_vor <- yam_35 %>% 
  st_join(sitecentroid_voronyi, left = TRUE, st_intersects) #actual polygons

yam_vor_buf <- yam_35 %>% 
  st_join(y_sites_buf,left = TRUE, st_intersects) %>% 
  st_join(sitecentroid_voronyi, left = TRUE, st_intersects) #actual polygons

plot(siteborder_voronyi$geometry);plot(y_sites_buf$geometry,add=T)
yam_vor_buf
names(yam_vor_buf)

# Resulting number of polygons inside site Voronyi polygons
yam_vor %>% 
  st_drop_geometry() %>% 
  group_by(TRAP_Code) %>% 
  tally() %>% 
  arrange(n)
  arrange(desc(n))
# 197-516 units in the 10 largest Vor polygons!
# over 100 units in the 38 largest Vor polygons

plot(yam_vor$geometry, col = yam_vor$TRAP_Code)


# Buffer helps! I get 1-99 units per site, there may still be overlap
yam_vor_buf%>% 
  st_drop_geometry() %>% 
  group_by(TRAP_Code.x) %>% 
  tally() %>% 
  arrange(n) %>% 
  #arrange(desc(n)) %>% 
  slice(1:15)

# Compare the results of OC_code assignment 
plot(yam_vor_buf$geometry, col = yam_vor_buf$TRAP_Code.x); plot(y_sitesu$geometry, border = "cyan", cex = 3, add = T)
   
plot(yam_vor$geometry, col = yam_vor$TRAP_Code); plot(y_sitesu$geometry, border = "cyan", cex = 3, add = T)


# Check how many polygons remain unassigned 
sum(is.na(yam_vor_buf$TRAP_Code.x)) # 4211 units lack a site id -Manual! 
sum(is.na(yam_vor$TRAP_Code)) # 156 lack a site ID


# Plot the units in their buffer
yam_vor_buf %>% 
  filter(!is.na(TRAP_Code.x)) %>% 
  mapview(zcol = "TRAP_Code.x") + mapview(sitecentroid_voronyi)

yam_vor %>% 
  filter(!is.na(TRAP_Code)) %>% 
  mapview(zcol = "TRAP_Code") + mapview(y_sites)

plot(yam_master)
# Export these units:
st_write(yam_vor_buf, "data_output/yam_vor_buf.geojson")
st_write(yam_vor, "data_output/yam_vor.geojson")
st_write(siteborder_voronyi, "data_output/border_voronyi.geojson")
st_write(sitecentroid_voronyi,"data_output/centroid_voronyi.geojson")
st_write(y_sites, "data_output/sitepolys.geojson")
st_write(yam_sites, "data_output/sitepoints.geojson")
st_write(yam_master, "data_output/yam_master_buf.geojson")

# Export for Angel

st_write(siteborder_voronyi, "data_output/yam_border_voronyi.shp")
st_write(sitecentroid_voronyi, "data_output/yam_centroid_voronyi.shp")
st_write(yam_vor[,c("SUID","TRAP_Code")], "data_output/yam_units_vor.shp")

st_write(yam_vor_buf[,c("SUID","TRAP_Code.x")], "data_output/yam_units_vor_buf.shp")

test <- read_sf("data_output/yam_units_vor.shp")
plot(test$geometry, col = test$TRAP_Code)
