# OC data: creating spatial hierarchy for Eric Kansa April 2023

# This script explores
# 1. VOronyi approach
# 2. Buffers approach
# 3. Select by distance approach
# 4. might look at neighborhood approach?

# merge units with sites and generate a column that lists either the site TRAP id, or a nonsite_1, nonsite_2. You can use Voronyi polygons too. 

library(sf)
library(raster)
library(tidyverse)

# Choose which computer you are on
path <- "C:/Users/Adela/OneDrive/Desktop/TRAP_Oxbow/"  # path for W11
#path <- "C:/Users/adela/Desktop/TRAP_Oxbow/"        # path for W10

# Load survey polygons
kaz <- read_sf("C:/Users/adela/Downloads/kaz-survey-units-reproj-w-uuids-fixed.geojson")
yam <- read_sf("C:/Users/adela/Downloads/yam-survey-units-reproj-w-uuids.geojson")

kaz_35 <- st_transform(kaz, 32635)

plot(yam$geometry)
plot(kaz$geometry)
  

names(kaz)
st_crs(kaz)

# Load site polygons
k_sites <- read_sf(paste0(path, "KAZ/KAZ_margins.shp"))


names(k_sites)
plot(k_sites$geometry)


#  Load site centroids

kaz_sites <- read_sf(paste0(path, "KAZ/KAZ_scatterpoints.shp"))
yam_sites<- read_sf(paste0(path, "YAM/YAM_scatterpoints.shp"))
plot(kaz$geometry);plot(st_transform(kaz_sites$geometry, 4326), cex = 2, col = "red", add = T)

# Create buffers
kaz_sites_buf <- st_buffer(kaz_sites, dist = 250)
k_sites_buf <- st_buffer(k_sites, dist = 100)

plot(k_sites_buf$geometry); plot(k_sites$geometry, add = TRUE)

library(mapview)
mapview(kaz_sites_buf) + mapview(k_sites_buf)
# Load site attributes (chronology)


################################ Join sites and polygons WHY?
# Check for spatial join 
# to join attributes 

kaz_join_site <- kaz %>% 
  st_transform(32635) %>% 
  st_join(k_sites[,4:8])

kaz_join_site
colnames(kaz_join_site)
tail(kaz_join_site[30:36])

# check what groupings you get now


###################### Voronyi approach
?st_voronoi()


# need bounding box for Kaz survey coverage as a second argument

kaz_master <- kaz %>% 
  st_transform(32635) %>% 
  st_simplify(dTolerance = 50) %>% 
  st_union(by_feature = F) %>% 
  st_buffer(1000)

plot(kaz_master)
st_bbox(kaz_master)
st_bbox(kaz_sites)

border <- st_as_sfc(st_bbox(kaz_sites)) %>% 
  st_set_crs(NA)
point <- st_sfc(kaz_sites$geometry)
st_crs(border)==st_crs(point)

# Not sure what I did below???
# voronyi <- st_intersection(st_collection_extract(st_voronoi(do.call(c,point))),border)
# st_crs(voronyi) <- 32635
# mapview(voronyi)
?st_voronoi

# Create Voronyi polygons 
k_sitepoint_voronyi <- st_voronoi(st_union(kaz_sites), envelope = st_as_sfc(st_bbox(kaz_sites)))
k_sitepoly_voronyi <- st_voronoi(st_union(st_centroid(k_sites)), envelope = st_as_sfc(st_bbox(k_sites)))

# Extract the actual polygons from the collection
sitecentroid_voronyi <- st_collection_extract(k_sitepoint_voronyi)
siteborder_voronyi <- st_collection_extract(k_sitepoly_voronyi)

# Plot voronyi polygons around scatter points and polygon centroids
plot(sitecentroid_voronyi); plot(siteborder_voronyi, border = "red", add = T)

# Plot the voronyi polygons around scatter points
plot(kaz_master, col = "pink")
plot(sitecentroid_voronyi, add = T)
plot(kaz_sites$geometry, add =T)
plot(st_as_sfc(st_bbox(kaz_sites$geometry)), add =T)


# plot voronyi polygons around autogenerated centroids
plot(kaz_master, col = "pink")
plot(siteborder_voronyi, add = T)
plot(kaz_sites$geometry, add =T)
plot(st_as_sfc(st_bbox(k_sites$geometry)), add =T)

# plot with mapview to zoom in and check on things
mapview(st_sf(siteborder_voronyi)) + mapview(k_sites)+ mapview (kaz_master)


## Reduce Voronyi polygons to survey area

plot(st_intersection(sitecentroid_voronyi, kaz_master)); plot(k_sites$geometry, add = T)
sitecentroid_voronyi <- st_intersection(sitecentroid_voronyi, kaz_master)
siteborder_voronyi <- st_intersection(siteborder_voronyi, kaz_master)

plot(siteborder_voronyi)
plot(k_sites$geometry, add = T, col = "purple")

## Join Voronyi with site information
sitecentroid_voronyi <- st_join(st_sf(sitecentroid_voronyi), st_sf(kaz_sites))
siteborder_voronyi <- st_join(st_sf(siteborder_voronyi), st_sf(kaz_sites))

length(unique(siteborder_voronyi$TRAP_Code))

# Visualise with survey polygons
plot(kaz_sites$geometry)
plot(siteborder_voronyi$geometry, col = siteborder_voronyi$TRAP_Code, alpha = 0.5, add =T)
plot(st_transform(kaz$geometry, 32635), add =T)

# Intersect survey polygons with Voronyi polygons
list_vor_per_unit <- st_intersects(kaz_35,sitecentroid_voronyi)

list_units_per_vor <- st_intersects(sitecentroid_voronyi, kaz_35) # list of intersecting units

# Intersection (DOES NOT WORK due to topology)
units_w_vor <- st_intersection(kaz_35,sitecentroid_voronyi)
?st_intersection
# to handle lists, I need something alongside: # https://gis.stackexchange.com/questions/375177/in-r-how-do-i-generate-r-random-sample-of-contiguous-polygons

# INtersection sideways
kaz_vor <- kaz_35 %>% 
  st_join(sitecentroid_voronyi, left = TRUE, st_intersects) #actual polygons

kaz_vor_buf <- kaz_35 %>% 
  st_join(k_sites_buf,left = TRUE, st_intersects) %>% 
  st_join(sitecentroid_voronyi, left = TRUE, st_intersects) #actual polygons
  
plot(siteborder_voronyi$geometry);plot(k_sites_buf$geometry,add=T)
kaz_vor_buf
names(kaz_vor_buf)

# Resulting number of polygons inside site Voronyi polygons
kaz_vor %>% 
  st_drop_geometry() %>% 
  group_by(TRAP_Code) %>% 
  tally() %>% 
  arrange(desc(n))
# 250-408 units in the 10 largest Vor polygons!
# over 100 units in the 38 largest Vor polygons


# Buffer helps! I get 1-99 units per site, there may still be overlap
kaz_vor_buf%>% 
  st_drop_geometry() %>% 
  group_by(TRAP_Code.x) %>% 
  tally() %>% 
  arrange(desc(n))

sum(is.na(kaz_vor_buf$TRAP_Code.x)) # 7000 units lack a site id -Manual! 



# Plot the units in their buffer
kaz_vor_buf %>% 
  filter(!is.na(TRAP_Code.x)) %>% 
  mapview(zcol = "TRAP_Code.x") + mapview(sitecentroid_voronyi)

kaz_vor %>% 
  filter(!is.na(TRAP_Code)) %>% 
  mapview(zcol = "TRAP_Code") + mapview(k_sites)

plot(kaz_master)
# Export these units:
st_write(kaz_vor_buf, "data_output/kaz_vor_buf.geojson")
st_write(kaz_vor, "data_output/kaz_vor.geojson")
st_write(siteborder_voronyi, "data_output/border_voronyi.geojson")
st_write(sitecentroid_voronyi,"data_output/centroid_voronyi.geojson")
st_write(k_sites, "data_output/sitepolys.geojson")
st_write(kaz_sites, "data_output/sitepoints.geojson")
st_write(kaz_master, "data_output/kaz_master_buf.geojson")

# Export for Angel

st_write(siteborder_voronyi, "data_output/border_voronyi.shp")
st_write(sitecentroid_voronyi, "data_output/centroid_voronyi.shp")
st_write(kaz_vor[,c("SUID","TRAP_Code")], "data_output/units_vor.shp")

st_write(kaz_vor_buf[,c("SUID","TRAP_Code.x")], "data_output/units_vor_buf.shp")
read_sf("data_output/units_vor_buf.shp")

# OBSOLETE BELOW
################### Inside-Buffer polygons

# kaz_35 %>%
#   filter(st_intersects(geometry, st_buffer(kaz_sites,500),
#                        sparse = FALSE))
  
buffer500 <- st_buffer(kaz_sites, 500) 

kaz_sitebuf <- kaz_35 %>% 
  st_join(buffer500, st_intersects)
colnames(kaz_sitebuf)

list_sitebuf <- kaz_sitebuf %>% 
  st_drop_geometry() %>% 
  group_by(TRAP_Code) %>% 
  tally() %>% 
  arrange(desc(n))

print(list_sitebuf, n=72)


################### Nearest polygons

nearest <- st_nearest_feature(kaz_sites,st_centroid(kaz_35))

# distance-based k neighbors (no need to touch)
library(spdep)
nearest50 <- knn2nb(knearneigh(st_centroid(kaz_35), k = 50))
nearest_to_site <- st_nearest_feature(kaz_sites, kaz_35)

# subsetting a list of indeces (not entirely successful)
nb <- nearest50[nearest_to_site] # clearly there's overlap

# lets see how many unique unit indeces are there
units <- unique(unlist(nb))

# select the unit polygons by index number
near50polygons <- kaz_35[units,]

# plot the 50 nearest polygons for all sites (minus duplicates)
plot(kaz_sites$geometry);plot(near50polygons$geometry, add=T)

mapview(kaz_sites)+mapview(near50polygons)

#### I need to select the 50 nearest polys within the Voronyi polygons?
# then there will be less overlap
# but it will be an artificial division